env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  ldflags:
    - -X main.Version={{ .Version }}
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
brew:
  github:
    owner: micnncim
    name: homebrew-tap
  folder: Formula
  homepage:  https://github.com/micnncim/goreleaser-playground
  description: GoReleaser playground
  test: |
    system "#{bin}/goreleaser-playground -v"
scoop:
  bucket:
    owner: micnncim
    name: scoop-bucket
  homepage:  https://github.com/micnncim/goreleaser-playground
  description: GoReleaser playground
  license: MIT

