# This file was generated by GoReleaser. DO NOT EDIT.
class GoreleaserPlayground < Formula
  desc "GoReleaser playground"
  homepage "https://github.com/micnncim/goreleaser-playground"
  url "https://github.com/micnncim/goreleaser-playground/releases/download/v0.2.1/goreleaser-playground_0.2.1_darwin_amd64.tar.gz"
  version "0.2.1"
  sha256 "76c28a6d30ed300dfb2c9d92a8aa7b3125d131f317faa4a312db00fcb3b0bdef"

  def install
    bin.install "goreleaser-playground"
  end

  test do
    system "#{bin}/goreleaser-playground -v"
  end
end
